/**
 * Heuristics for keeping secrets out of the vault. Passive clipboard capture
 * must never index a password or API key: one leaked credential outweighs a
 * thousand remembered links. Deliberately conservative — false positives cost
 * one lost clipboard entry, false negatives cost trust.
 */

const SECRET_PATTERNS: { name: string; re: RegExp }[] = [
  { name: 'private key block', re: /-----BEGIN [A-Z ]*PRIVATE KEY-----/ },
  { name: 'AWS access key', re: /\b(AKIA|ASIA)[0-9A-Z]{16}\b/ },
  { name: 'GitHub token', re: /\bgh[pousr]_[A-Za-z0-9]{30,}\b/ },
  { name: 'GitLab token', re: /\bglpat-[A-Za-z0-9_-]{20,}\b/ },
  { name: 'Slack token', re: /\bxox[baprs]-[A-Za-z0-9-]{10,}\b/ },
  { name: 'Google API key', re: /\bAIza[0-9A-Za-z_-]{35}\b/ },
  { name: 'Anthropic key', re: /\bsk-ant-[A-Za-z0-9_-]{20,}\b/ },
  { name: 'OpenAI-style key', re: /\bsk-(proj-)?[A-Za-z0-9_-]{20,}\b/ },
  { name: 'Stripe secret key', re: /\b[sr]k_live_[0-9a-zA-Z]{20,}\b/ },
  { name: 'JWT', re: /\beyJ[A-Za-z0-9_-]{10,}\.eyJ[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{10,}\b/ },
  { name: 'connection string with password', re: /\b\w+:\/\/[^\s:@/]+:[^\s@/]{4,}@[^\s@]+/ },
  { name: 'assignment of a credential', re: /^\s*(export\s+)?[A-Z0-9_]*(PASSWORD|PASSWD|SECRET|TOKEN|API_?KEY|PRIVATE_?KEY)[A-Z0-9_]*\s*[=:]\s*\S+/im },
];

/**
 * A single opaque token with the shape of a generated password or key:
 * one line, no spaces, mixed character classes, no URL/prose features.
 */
function looksLikeOpaqueToken(text: string): boolean {
  const t = text.trim();
  if (t.length < 20 || t.length > 128) return false;
  if (/\s/.test(t)) return false;
  if (/^https?:\/\//i.test(t)) return false;
  if (/^[/~.]/.test(t)) return false; // file paths
  if (!/^[A-Za-z0-9+/=_.~!@#$%^&*-]+$/.test(t)) return false;
  // Domains and file paths read as words separated by dots/slashes — skip
  // anything with a lowercase-words-and-dots shape.
  if (/^[a-z0-9-]+(\.[a-z0-9-]+)+(\/\S*)?$/i.test(t)) return false;
  const hasLower = /[a-z]/.test(t);
  const hasUpper = /[A-Z]/.test(t);
  const hasDigit = /\d/.test(t);
  const hasSymbol = /[+/=_.~!@#$%^&*-]/.test(t);
  return hasDigit && hasLower && (hasUpper || hasSymbol);
}

/** Returns the reason the text looks secret, or null if it looks safe. */
export function detectSecret(text: string): string | null {
  for (const { name, re } of SECRET_PATTERNS) {
    if (re.test(text)) return name;
  }
  if (looksLikeOpaqueToken(text)) return 'opaque token';
  return null;
}

/**
 * Password managers and secret stores: anything copied while one of these is
 * frontmost is assumed to be a credential.
 */
const BLOCKED_APPS = [
  '1password', 'bitwarden', 'keepass', 'dashlane', 'lastpass', 'keeper',
  'proton pass', 'protonpass', 'enpass', 'nordpass', 'strongbox',
  'keychain access', 'passwords', // macOS Passwords.app / Keychain Access
];

export function isBlockedApp(appName: string): boolean {
  const n = appName.toLowerCase();
  return BLOCKED_APPS.some(b => n.includes(b));
}

/**
 * Well-behaved password managers mark clipboard writes with
 * org.nspasteboard.ConcealedType (see nspasteboard.org). `osascript -e
 * 'clipboard info'` output is checked for those markers.
 */
export function isConcealedClipboard(clipboardInfo: string): boolean {
  return /org\.nspasteboard\.(ConcealedType|AutoGeneratedType)/i.test(clipboardInfo);
}
